### ISSUE TITLE
Medium embeddings are bugged

### ISSUE THREAD

**Issue by studosi-flarum** [FriendsOfFlarum/formatting#11]
Well, there is not much to say. Medium embeddings look somewhat fine in the post preview, but when inserted, they are cut off and they don't actually show the link of the article that was linked:

![image](https://user-images.githubusercontent.com/62252935/77235654-17763a00-6bb8-11ea-9939-17186b47c7ad.png)

I realize that this might be due to Medium changing their API, but it is nevertheless an issue.

**Comment by datitisev** [comment]
Works completely fine for me. Check your custom CSS?

Also - issues with the plugins (Autoimage, Autovideo...) themselves will not be introduced by this extension, as they are coded in s9e/TextFormatter and just enabled through this extension.

![image](https://user-images.githubusercontent.com/6401250/77235791-32808400-6b8f-11ea-8a6a-7dd08f88bf62.png)

**Comment by studosi-flarum** [comment]
I've tested this on a local build, and there was no issue either. I've included my custom CSS on there but it worked still. This might be due to an extension, and since I have most of the extensions on my local build, I can narrow it down.

If I don't find any problems, I'll update the post with my `php flarum info` and all the other things I left out.

**Comment by datitisev** [comment]
If you find which extension causes the problem, I'd suggest creating an issue in their repo as this extension does not include any styling or code for the plugins - they are already coded (by someone else) and simply enabled.

**Comment by studosi-flarum** [comment]
Alright, I have found this issue - it was the hashtags plugin. As you've said, it's their issue to fix. I had already tested the custom CSS (as you usually should), so I just automatically assumed it was the extension being broken, because I saw this working before, even when all the extensions I had were already installed.

Thanks for your time and sorry for the inconvenience.

**Comment by datitisev** [comment]
No problem. Glad you figured the source of the problem quickly 🙂
