### ISSUE TITLE
lazy load for videos?

### ISSUE THREAD

**Issue by BigMinnie** [FriendsOfFlarum/formatting#12]
I have a discussion with tons of videos (100+) an the load time is crazy. Could something be done with this? Maybe some lazy loading when it starts loading the video the only time you click on it?

**Comment by datitisev** [comment]
This extension only enables existing s9e/TextFormatter plugins. It does not configure anything apart from that. To implement lazy loading you'd need to use different code than the s9e Autovideo / Mediaembed provides, and I don't think that's in the scope of this extension.

**Comment by BigMinnie** [comment]
oh ok thanks for the info
