### ISSUE TITLE
Add Support to Spotify

### ISSUE THREAD

**Issue by danielunited** [FriendsOfFlarum/formatting#18]
Spotify changed the way they generate links to communities (example: https://link.tospotify.com/fzU48B0mLbb)

s9e/TextFormatter added support to it a few days ago, I'm wondering if we can include it too?

Thanks!

**Comment by clarkwinkelmann** [comment]
You should be able to just run `composer update s9e/text-formatter`.

On either beta 13 or beta 14 this should make TextFormatter jump to 2.7.6

**Comment by danielunited** [comment]
Works!
