### ISSUE TITLE
TypeError thrown with message "Argument 1 passed to Flarum\Mentions\Formatter\FormatPostMentions

### ISSUE THREAD

**Issue by fstln-joe** [FriendsOfFlarum/formatting#23]
TypeError thrown with message "Argument 1 passed to Flarum\Mentions\Formatter\FormatPostMentions::__invoke() must be an instance of s9e\TextFormatter\Renderer, instance of __PHP_Incomplete_Class given, called in /data/WWW/vendor/flarum/core/src/Foundation/ContainerUtil.php on line 30"

Stacktrace:
#62 TypeError in /data/WWW/vendor/flarum/mentions/src/Formatter/FormatPostMentions.php:27
#61 Flarum\Mentions\Formatter\FormatPostMentions:__invoke in /data/WWW/vendor/flarum/core/src/Foundation/ContainerUtil.php:30
#60 Flarum\Foundation\ContainerUtil:Flarum\Foundation\{closure} in /data/WWW/vendor/flarum/core/src/Formatter/Formatter.php:91
#59 Flarum\Formatter\Formatter:render in /data/WWW/vendor/flarum/core/src/Post/CommentPost.php:172
#58 Flarum\Post\CommentPost:formatContent in /data/WWW/vendor/flarum/core/src/Api/Serializer/BasicPostSerializer.php:44
#57 Flarum\Api\Serializer\BasicPostSerializer:getDefaultAttributes in /data/WWW/vendor/flarum/core/src/Api/Serializer/AbstractSerializer.php:87
#56 Flarum\Api\Serializer\AbstractSerializer:getAttributes in /data/WWW/vendor/tobscure/json-api/src/Resource.php:169
#55 Tobscure\JsonApi\Resource:getAttributes in /data/WWW/vendor/tobscure/json-api/src/Resource.php:75
#54 Tobscure\JsonApi\Resource:toArray in /data/WWW/vendor/tobscure/json-api/src/Document.php:187
#53 Tobscure\JsonApi\Document:Tobscure\JsonApi\{closure} in [internal]:0
#52 array_map in /data/WWW/vendor/tobscure/json-api/src/Document.php:186
#51 Tobscure\JsonApi\Document:toArray in /data/WWW/vendor/tobscure/json-api/src/Document.php:224
#50 Tobscure\JsonApi\Document:jsonSerialize in /data/WWW/vendor/flarum/core/src/Api/JsonApiResponse.php:27
#49 Flarum\Api\JsonApiResponse:__construct in /data/WWW/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php:121
#48 Flarum\Api\Controller\AbstractSerializeController:handle in /data/WWW/vendor/flarum/core/src/Api/Client.php:72
#47 Flarum\Api\Client:send in /data/WWW/vendor/flarum/core/src/Forum/Content/Index.php:121
#46 Flarum\Forum\Content\Index:getApiDocument in /data/WWW/vendor/flarum/core/src/Forum/Content/Index.php:86
#45 Flarum\Forum\Content\Index:__invoke in /data/WWW/vendor/flarum/core/src/Frontend/Frontend.php:63
#44 Flarum\Frontend\Frontend:populate in /data/WWW/vendor/flarum/core/src/Frontend/Frontend.php:55
#43 Flarum\Frontend\Frontend:document in /data/WWW/vendor/flarum/core/src/Frontend/Controller.php:32
#42 Flarum\Frontend\Controller:handle in /data/WWW/vendor/flarum/core/src/Http/RouteHandlerFactory.php:38
#41 Flarum\Http\RouteHandlerFactory:Flarum\Http\{closure} in /data/WWW/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php:27
#40 Flarum\Http\Middleware\ExecuteRoute:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#39 Laminas\Stratigility\Next:handle in /data/WWW/packages/flarum-ext-sso/src/Middleware/LogoutMiddleware.php:24
#38 Fstln\SSO\Middleware\LogoutMiddleware:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#37 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php:29
#36 Flarum\Http\Middleware\FlarumPromotionHeader:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#35 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php:57
#34 Flarum\Http\Middleware\ShareErrorsFromSession:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#33 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php:36
#32 Flarum\Http\Middleware\CheckCsrfToken:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#31 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php:67
#30 Flarum\Http\Middleware\ResolveRoute:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#29 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/SetLocale.php:50
#28 Flarum\Http\Middleware\SetLocale:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#27 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php:32
#26 Flarum\Http\Middleware\AuthenticateWithSession:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#25 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php:52
#24 Flarum\Http\Middleware\RememberFromCookie:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#23 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/StartSession.php:61
#22 Flarum\Http\Middleware\StartSession:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#21 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php:46
#20 Flarum\Http\Middleware\CollectGarbage:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#19 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php:28
#18 Flarum\Http\Middleware\ParseJsonBody:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#17 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/HandleErrors.php:57
#16 Flarum\Http\Middleware\HandleErrors:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#15 Laminas\Stratigility\Next:handle in /data/WWW/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php:84
#14 Laminas\Stratigility\MiddlewarePipe:process in /data/WWW/vendor/middlewares/request-handler/src/RequestHandler.php:84
#13 Middlewares\RequestHandler:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#12 Laminas\Stratigility\Next:handle in /data/WWW/vendor/middlewares/base-path-router/src/BasePathRouter.php:101
#11 Middlewares\BasePathRouter:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#10 Laminas\Stratigility\Next:handle in /data/WWW/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php:42
#9 Laminas\Stratigility\Middleware\OriginalMessages:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#8 Laminas\Stratigility\Next:handle in /data/WWW/vendor/middlewares/base-path/src/BasePath.php:53
#7 Middlewares\BasePath:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#6 Laminas\Stratigility\Next:handle in /data/WWW/vendor/flarum/core/src/Http/Middleware/ProcessIp.php:24
#5 Flarum\Http\Middleware\ProcessIp:process in /data/WWW/vendor/laminas/laminas-stratigility/src/Next.php:61
#4 Laminas\Stratigility\Next:handle in /data/WWW/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php:84
#3 Laminas\Stratigility\MiddlewarePipe:process in /data/WWW/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php:73
#2 Laminas\Stratigility\MiddlewarePipe:handle in /data/WWW/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php:96
#1 Laminas\HttpHandlerRunner\RequestHandlerRunner:run in /data/WWW/vendor/flarum/core/src/Http/Server.php:44
#0 Flarum\Http\Server:listen in /data/WWW/public/index.php:26

--------
Flarum core 0.1.0-beta.16
PHP version: 7.4.12
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, pdo_mysql, shmop, SimpleXML, soap, sockets, mysqli, sysvsem, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, fileinfo, redis
+-----------------------------------+----------------+--------+
| Flarum Extensions                 |                |        |
+-----------------------------------+----------------+--------+
| ID                                | Version        | Commit |
+-----------------------------------+----------------+--------+
| flarum-flags                      | v0.1.0-beta.16 |        |
| flarum-markdown                   | v0.1.0-beta.16 |        |
| fstln-footer                      | dev-nothing    |        |
| flarum-bbcode                     | v0.1.0-beta.16 |        |
| flarum-emoji                      | v0.1.0-beta.16 |        |
| flarum-lang-english               | v0.1.0-beta.16 |        |
| flarum-lock                       | v0.1.0-beta.16 |        |
| flarum-mentions                   | v0.1.0-beta.16 |        |
| flarum-sticky                     | v0.1.0-beta.16 |        |
| flarum-suspend                    | v0.1.0-beta.16 |        |
| flarum-tags                       | v0.1.0-beta.16 |        |
| flarum-statistics                 | v0.1.0-beta.16 |        |
| flarum-likes                      | v0.1.0-beta.16 |        |
| fstln-news                        | dev-nothing    |        |
| fof-polls                         | 0.3.2          |        |
| fstln-sso                         | dev-nothing    |        |
| fstln-bio                         | dev-nothing    |        |
| fstln-nothing-theme               | dev-nothing    |        |
| flarum-approval                   | v0.1.0-beta.16 |        |
| askvortsov-rich-text              | v1.0.2         |        |
| flarumite-simple-discussion-views | 0.3.0          |        |
+-----------------------------------+----------------+--------+

**Comment by datitisev** [comment]
This is not an issue with fof/formatting.

See https://discuss.flarum.org/d/25472-beta-14-update-leaves-only-some-users-unable-to-see-discussions/10 for a solution to this issue.

**Comment by imorland** [comment]
This is caused by your forum's cache not clearing or rebuilding correctly.

Can you please try clearing the cache manually, either from the admin panel or `php flarum cache:clear` from the CLI?
