### ISSUE TITLE
Unable to display video controls

### ISSUE THREAD

**Issue by p4st0r** [FriendsOfFlarum/formatting#3]
**How can I display the video playback control, because the video uploads without controls, the user will mistake the video card for death.**

**Comment by datitisev** [comment]
Erm, what plugin are you using? Mediaembed or autovideo? Either way, this sounds like an issue with TextFormatter. This extension does _not_ add the plugins, just enables them.

**Comment by p4st0r** [comment]
I guess this issue is about Mediaembed, still hasn't solved it yet.

**Comment by datitisev** [comment]
What video site are you trying to embed?

**Comment by p4st0r** [comment]
The URL addrss just like https://baidu.com/1.mp4

**Comment by datitisev** [comment]
That would most likely be caused by Autovideo. Autovideo embeds video files, mediaembed embeds media websites.

In theory, it _should_ have the controls (https://s9etextformatter.readthedocs.io/Plugins/Autovideo/Synopsis/). Do you have a live url where we can see this?

**Comment by p4st0r** [comment]
Of course, if you want you can visit my flarum forum https://bbs.zhuran.org/d/53-2019-3-16 and to see what happened with my extension

**Comment by p4st0r** [comment]
At the bottom of the forum, I introduced a cat's video link. He needs to right-click on the playback control to finish playing.

**Comment by datitisev** [comment]
Hm... what's the posts content? Did you use flagrow/upload to upload that file? I don't think that one is being managed by Autovideo. The videos on the first post seem to be.

**Comment by p4st0r** [comment]
Right, I use flagrow/upload to upload that file. Is it because this expands to the problem?

**Comment by luceos** [comment]
Files uploaded by the flagrow upload extension are parsed differently. Either you retrieve their full URL after uploading and use that in your content or you upload the file somewhere else.
I'll look into a solution for this in upload once I make it more advanced in the future.
