### ISSUE TITLE
 TeamPiped / Piped 

### ISSUE THREAD

**Issue by Profi420** [FriendsOfFlarum/formatting#36]
## Feature Request

Could you please embed this for Youtube? 
https://github.com/TeamPiped/Piped

A clear and concise description of what the problem is. eg. I have an issue when [...]

YouTube has an extremely invasive privacy policy which relies on using user data in unethical ways. You give them a lot of data - ranging from ideas, music taste, content, political opinions, and much more than you think.

By using Piped, you can freely watch and listen to content without the fear of prying eyes watching everything you are doing.

A detailed description of your proposed solution. Include:
- How the feature would work/behave
- Any potential drawbacks
- Maybe a screenshot, design, or example code

**Describe alternatives you've considered**

**Comment by dsevillamartin** [comment]
Adding custom embeds for sites is not in the scope of this extension.
