### ISSUE TITLE
the html code was escaped

### ISSUE THREAD

**Issue by essesoul** [FriendsOfFlarum/formatting#37]
https://discuss.flarum.org/d/17770-friendsofflarum-formatting/399
I found that when I inserted the telegram link, the html code was escaped, so the content could not be displayed normally
After being escaped, it looks like this
`https://s9e.github.io/iframe/2/telegram.min.html%20%3Ca%20href=`

**Comment by dsevillamartin** [comment]
Just attempted to use a Telegram link and it embedded just fine. Can you provide more info?

In any case, if there is an issue, it's more likely that it is with the TextFormatter library and not this extension or Flarum. This extension only enables the MediaEmbed plugin in TextFormatter, it doesn't create it. So I'll close this for now.
