### ISSUE TITLE
Error booting Flarum

### ISSUE THREAD

**Issue by gkiosov** [FriendsOfFlarum/formatting#6]
Hello.

Installed fof/formating and received «Error booting Flarum: Class FoF\Formatting\Listeners\FormatterConfigurator does not exist» message in the browser (white screen) after activating it. 

All files in the place. Flarum is not working until I delete fof/formating from DB as an installed extension.

**Comment by datitisev** [comment]
That'd odd. Have you tried removing it & requiring it again with composer ? I don't see how that'd be an issue on our side...

**Comment by gkiosov** [comment]
> That'd odd. Have you tried removing it & requiring it again with composer ? I don't see how that'd be an issue on our side...
I requiring it locally because we have some problems with the composer on our shared hosting. Then I exported it to the hosted server as I did with other extensions — all of them works fine except of fof/formating.

Tried three times.

**Comment by datitisev** [comment]
Can you check to make sure `FoF\\Formatting\\` exists in `vendor/composer/autoload_psr4.php` ? The other extensions might've worked because they didn't contain other PHP files apart from `extend.php`...

It should look something like this:
```php
'FoF\\Formatting\\' => array($vendorDir . '/fof/formatting/src'),
```

**Comment by gkiosov** [comment]
> Can you check to make sure `FoF\\Formatting\\` exists in `vendor/composer/autoload_psr4.php` ? The other extensions might've worked because they didn't contain other PHP files apart from `extend.php`...
> 
> It should look something like this:
> 
> ```
> 'FoF\\Formatting\\' => array($vendorDir . '/fof/formatting/src'),
> ```

Dunno what's happened but I just remove both fof/formatting and old and unused s9e/mediaembed, and then requiring fof/formatting again. Everything is working fine now.

Thanks and sorry for this issue, looks like my bad.

**Comment by datitisev** [comment]
Hm, that's odd. Glad you got it sorted out. I didn't think it was an issue on our side.
